# Generated by Django 2.2.7 on 2019-11-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[(1, 'TODO'), (2, 'DOING'), (3, 'DONE')], max_length=10)),
            ],
        ),
    ]
